/**
 * Turn scratch/jadwalmisa_churches.json into supabase/069_seed_mass_churches.sql
 *   node scripts/generate_mass_sql.js
 */
const fs = require("fs");
const path = require("path");

const IN = path.join(__dirname, "..", "scratch", "jadwalmisa_churches.json");
const OUT = path.join(__dirname, "..", "supabase", "069_seed_mass_churches.sql");

const q = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const jsonb = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

const churches = JSON.parse(fs.readFileSync(IN, "utf8"));

const lines = [];
lines.push("-- 069_seed_mass_churches.sql");
lines.push("-- Generated by scripts/generate_mass_sql.js from public jadwalmisa.id data.");
lines.push(`-- ${churches.length} churches. Idempotent (ON CONFLICT DO UPDATE).`);
lines.push("");

const BATCH = 50;
for (let i = 0; i < churches.length; i += BATCH) {
  const rows = churches.slice(i, i + BATCH).map((c) => {
    return (
      "  (" +
      [
        c.id,
        q(c.name),
        q(c.slug),
        q(c.address),
        q(c.maps_url),
        q(c.image_url),
        q(c.time_zone),
        q(c.province_slug),
        q(c.province_name),
        q(c.regency_slug),
        q(c.regency_name),
        jsonb(c.schedules || []),
        jsonb(c.special_schedules || []),
        q(c.source_url),
      ].join(", ") +
      ")"
    );
  });

  lines.push(
    "INSERT INTO public.mass_churches (id, name, slug, address, maps_url, image_url, time_zone, province_slug, province_name, regency_slug, regency_name, schedules, special_schedules, source_url) VALUES"
  );
  lines.push(rows.join(",\n") + "");
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, address = EXCLUDED.address, maps_url = EXCLUDED.maps_url, image_url = EXCLUDED.image_url, time_zone = EXCLUDED.time_zone, province_slug = EXCLUDED.province_slug, province_name = EXCLUDED.province_name, regency_slug = EXCLUDED.regency_slug, regency_name = EXCLUDED.regency_name, schedules = EXCLUDED.schedules, special_schedules = EXCLUDED.special_schedules, source_url = EXCLUDED.source_url, synced_at = now();"
  );
  lines.push("");
}

fs.writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${path.relative(process.cwd(), OUT)} (${churches.length} rows, ${Math.ceil(churches.length / BATCH)} batches)`);
