-- ==========================================
-- BIBLE VERSES SEED DATA (TB & WEB)
-- ==========================================

INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 1, 'Adapun ular ialah yang paling cerdik dari segala binatang di darat yang dijadikan oleh TUHAN Allah. Ular itu berkata kepada perempuan itu: "Tentulah Allah berfirman: Semua pohon dalam taman ini jangan kamu makan buahnya, bukan?"', 'Now the serpent was more subtle than any animal of the field which Yahweh God had made. He said to the woman, “Has God really said, ‘You shall not eat of any tree of the garden?’”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 2, 'Lalu sahut perempuan itu kepada ular itu: "Buah pohon-pohonan dalam taman ini boleh kami makan,', 'The woman said to the serpent, “We may eat fruit from the trees of the garden,');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 3, 'tetapi tentang buah pohon yang ada di tengah-tengah taman, Allah berfirman: Jangan kamu makan ataupun raba buah itu, nanti kamu mati."', 'but not the fruit of the tree which is in the middle of the garden. God has said, ‘You shall not eat of it. You shall not touch it, lest you die.’”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 4, 'Tetapi ular itu berkata kepada perempuan itu: "Sekali-kali kamu tidak akan mati,', 'The serpent said to the woman, “You won’t really die,');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 5, 'tetapi Allah mengetahui, bahwa pada waktu kamu memakannya matamu akan terbuka, dan kamu akan menjadi seperti Allah, tahu tentang yang baik dan yang jahat."', 'for God knows that in the day you eat it, your eyes will be opened, and you will be like God, knowing good and evil.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 6, 'Perempuan itu melihat, bahwa buah pohon itu baik untuk dimakan dan sedap kelihatannya, lagipula pohon itu menarik hati karena memberi pengertian. Lalu ia mengambil dari buahnya dan dimakannya dan diberikannya juga kepada suaminya yang bersama-sama dengan dia, dan suaminyapun memakannya.', 'When the woman saw that the tree was good for food, and that it was a delight to the eyes, and that the tree was to be desired to make one wise, she took some of its fruit, and ate; and she gave some to her husband with her, and he ate it, too.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 7, 'Maka terbukalah mata mereka berdua dan mereka tahu, bahwa mereka telanjang; lalu mereka menyemat daun pohon ara dan membuat cawat.', 'Their eyes were opened, and they both knew that they were naked. They sewed fig leaves together, and made coverings for themselves.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 8, 'Ketika mereka mendengar bunyi langkah TUHAN Allah, yang berjalan-jalan dalam taman itu pada waktu hari sejuk, bersembunyilah manusia dan isterinya itu terhadap TUHAN Allah di antara pohon-pohonan dalam taman.', 'They heard Yahweh God’s voice walking in the garden in the cool of the day, and the man and his wife hid themselves from the presence of Yahweh God among the trees of the garden.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 9, 'Tetapi TUHAN Allah memanggil manusia itu dan berfirman kepadanya: "Di manakah engkau?"', 'Yahweh God called to the man, and said to him, “Where are you?”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 10, 'Ia menjawab: "Ketika aku mendengar, bahwa Engkau ada dalam taman ini, aku menjadi takut, karena aku telanjang; sebab itu aku bersembunyi."', 'The man said, “I heard your voice in the garden, and I was afraid, because I was naked; and I hid myself.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 11, 'Firman-Nya: "Siapakah yang memberitahukan kepadamu, bahwa engkau telanjang? Apakah engkau makan dari buah pohon, yang Kularang engkau makan itu?"', 'God said, “Who told you that you were naked? Have you eaten from the tree that I commanded you not to eat from?”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 12, 'Manusia itu menjawab: "Perempuan yang Kautempatkan di sisiku, dialah yang memberi dari buah pohon itu kepadaku, maka kumakan."', 'The man said, “The woman whom you gave to be with me, she gave me fruit from the tree, and I ate it.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 13, 'Kemudian berfirmanlah TUHAN Allah kepada perempuan itu: "Apakah yang telah kauperbuat ini?" Jawab perempuan itu: "Ular itu yang memperdayakan aku, maka kumakan."', 'Yahweh God said to the woman, “What have you done?”
The woman said, “The serpent deceived me, and I ate.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 14, 'Lalu berfirmanlah TUHAN Allah kepada ular itu: "Karena engkau berbuat demikian, terkutuklah engkau di antara segala ternak dan di antara segala binatang hutan; dengan perutmulah engkau akan menjalar dan debu tanahlah akan kaumakan seumur hidupmu.', 'Yahweh God said to the serpent,
“Because you have done this,
you are cursed above all livestock,
and above every animal of the field.
You shall go on your belly
and you shall eat dust all the days of your life.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 15, 'Aku akan mengadakan permusuhan antara engkau dan perempuan ini, antara keturunanmu dan keturunannya; keturunannya akan meremukkan kepalamu, dan engkau akan meremukkan tumitnya."', 'I will put hostility between you and the woman,
and between your offspring and her offspring.
He will bruise your head,
and you will bruise his heel.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 16, 'Firman-Nya kepada perempuan itu: "Susah payahmu waktu mengandung akan Kubuat sangat banyak; dengan kesakitan engkau akan melahirkan anakmu; namun engkau akan berahi kepada suamimu dan ia akan berkuasa atasmu."', 'To the woman he said,
“I will greatly multiply your pain in childbirth.
In pain you will bear children.
Your desire will be for your husband,
and he will rule over you.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 17, 'Lalu firman-Nya kepada manusia itu: "Karena engkau mendengarkan perkataan isterimu dan memakan dari buah pohon, yang telah Kuperintahkan kepadamu: Jangan makan dari padanya, maka terkutuklah tanah karena engkau; dengan bersusah payah engkau akan mencari rezekimu dari tanah seumur hidupmu:', 'To Adam he said,
“Because you have listened to your wife’s voice,
and ate from the tree,
about which I commanded you, saying, ‘You shall not eat of it,’
the ground is cursed for your sake.
You will eat from it with much labor all the days of your life.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 18, 'semak duri dan rumput duri yang akan dihasilkannya bagimu, dan tumbuh-tumbuhan di padang akan menjadi makananmu;', 'It will yield thorns and thistles to you;
and you will eat the herb of the field.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 19, 'dengan berpeluh engkau akan mencari makananmu, sampai engkau kembali lagi menjadi tanah, karena dari situlah engkau diambil; sebab engkau debu dan engkau akan kembali menjadi debu."', 'By the sweat of your face will you eat bread until you return to the ground,
for out of it you were taken.
For you are dust,
and to dust you shall return.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 20, 'Manusia itu memberi nama Hawa kepada isterinya, sebab dialah yang menjadi ibu semua yang hidup.', 'The man called his wife Eve because she would be the mother of all the living.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 21, 'Dan TUHAN Allah membuat pakaian dari kulit binatang untuk manusia dan untuk isterinya itu, lalu mengenakannya kepada mereka.', 'Yahweh God made coats of animal skins for Adam and for his wife, and clothed them.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 22, 'Berfirmanlah TUHAN Allah: "Sesungguhnya manusia itu telah menjadi seperti salah satu dari Kita, tahu tentang yang baik dan yang jahat; maka sekarang jangan sampai ia mengulurkan tangannya dan mengambil pula dari buah pohon kehidupan itu dan memakannya, sehingga ia hidup untuk selama-lamanya."', 'Yahweh God said, “Behold, the man has become like one of us, knowing good and evil. Now, lest he reach out his hand, and also take of the tree of life, and eat, and live forever—”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 23, 'Lalu TUHAN Allah mengusir dia dari taman Eden supaya ia mengusahakan tanah dari mana ia diambil.', 'Therefore Yahweh God sent him out from the garden of Eden, to till the ground from which he was taken.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (1, 'Kejadian', 'Genesis', 3, 24, 'Ia menghalau manusia itu dan di sebelah timur taman Eden ditempatkan-Nyalah beberapa kerub dengan pedang yang bernyala-nyala dan menyambar-nyambar, untuk menjaga jalan ke pohon kehidupan.', 'So he drove out the man; and he placed cherubim at the east of the garden of Eden, and a flaming sword which turned every way, to guard the way to the tree of life.');

INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (19, 'Mazmur', 'Psalms', 23, 1, 'Mazmur Daud. TUHAN adalah gembalaku, takkan kekurangan aku.', 'Yahweh is my shepherd:
I shall lack nothing.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (19, 'Mazmur', 'Psalms', 23, 2, 'Ia membaringkan aku di padang yang berumput hijau, Ia membimbing aku ke air yang tenang;', 'He makes me lie down in green pastures.
He leads me beside still waters.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (19, 'Mazmur', 'Psalms', 23, 3, 'Ia menyegarkan jiwaku. Ia menuntun aku di jalan yang benar oleh karena nama-Nya.', 'He restores my soul.
He guides me in the paths of righteousness for his name’s sake.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (19, 'Mazmur', 'Psalms', 23, 4, 'Sekalipun aku berjalan dalam lembah kekelaman, aku tidak takut bahaya, sebab Engkau besertaku; gada-Mu dan tongkat-Mu, itulah yang menghibur aku.', 'Even though I walk through the valley of the shadow of death,
I will fear no evil, for you are with me.
Your rod and your staff,
they comfort me.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (19, 'Mazmur', 'Psalms', 23, 5, 'Engkau menyediakan hidangan bagiku, di hadapan lawanku; Engkau mengurapi kepalaku dengan minyak; pialaku penuh melimpah.', 'You prepare a table before me
in the presence of my enemies.
You anoint my head with oil.
My cup runs over.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (19, 'Mazmur', 'Psalms', 23, 6, 'Kebajikan dan kemurahan belaka akan mengikuti aku, seumur hidupku; dan aku akan diam dalam rumah TUHAN sepanjang masa.', 'Surely goodness and loving kindness shall follow me all the days of my life,
and I will dwell in Yahweh’s house forever.');

INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 1, 'Adalah seorang Farisi yang bernama Nikodemus, seorang pemimpin agama Yahudi.', 'Now there was a man of the Pharisees named Nicodemus, a ruler of the Jews.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 2, 'Ia datang pada waktu malam kepada Yesus dan berkata: "Rabi, kami tahu, bahwa Engkau datang sebagai guru yang diutus Allah; sebab tidak ada seorangpun yang dapat mengadakan tanda-tanda yang Engkau adakan itu, jika Allah tidak menyertainya."', 'The same came to him by night, and said to him, “Rabbi, we know that you are a teacher come from God, for no one can do these signs that you do, unless God is with him.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 3, 'Yesus menjawab, kata-Nya: "Aku berkata kepadamu, sesungguhnya jika seorang tidak dilahirkan kembali, ia tidak dapat melihat Kerajaan Allah."', 'Jesus answered him,
“Most certainly, I tell you, unless one is born anew,

he can’t see God’s Kingdom.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 4, 'Kata Nikodemus kepada-Nya: "Bagaimanakah mungkin seorang dilahirkan, kalau ia sudah tua? Dapatkah ia masuk kembali ke dalam rahim ibunya dan dilahirkan lagi?"', 'Nicodemus said to him, “How can a man be born when he is old? Can he enter a second time into his mother’s womb, and be born?”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 5, 'Jawab Yesus: "Aku berkata kepadamu, sesungguhnya jika seorang tidak dilahirkan dari air dan Roh, ia tidak dapat masuk ke dalam Kerajaan Allah.', 'Jesus answered,
“Most certainly I tell you, unless one is born of water and spirit, he can’t enter into God’s Kingdom.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 6, 'Apa yang dilahirkan dari daging, adalah daging, dan apa yang dilahirkan dari Roh, adalah roh.', 'That which is born of the flesh is flesh. That which is born of the Spirit is spirit.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 7, 'Janganlah engkau heran, karena Aku berkata kepadamu: Kamu harus dilahirkan kembali.', 'Don’t marvel that I said to you, ‘You must be born anew.’');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 8, 'Angin bertiup ke mana ia mau, dan engkau mendengar bunyinya, tetapi engkau tidak tahu dari mana ia datang atau ke mana ia pergi. Demikianlah halnya dengan tiap-tiap orang yang lahir dari Roh."', 'The wind
blows where it wants to, and you hear its sound, but don’t know where it comes from and where it is going. So is everyone who is born of the Spirit.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 9, 'Nikodemus menjawab, katanya: "Bagaimanakah mungkin hal itu terjadi?"', 'Nicodemus answered him, “How can these things be?”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 10, 'Jawab Yesus: "Engkau adalah pengajar Israel, dan engkau tidak mengerti hal-hal itu?', 'Jesus answered him,
“Are you the teacher of Israel, and don’t understand these things?');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 11, 'Aku berkata kepadamu, sesungguhnya kami berkata-kata tentang apa yang kami ketahui dan kami bersaksi tentang apa yang kami lihat, tetapi kamu tidak menerima kesaksian kami.', 'Most certainly I tell you, we speak that which we know, and testify of that which we have seen, and you don’t receive our witness.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 12, 'Kamu tidak percaya, waktu Aku berkata-kata dengan kamu tentang hal-hal duniawi, bagaimana kamu akan percaya, kalau Aku berkata-kata dengan kamu tentang hal-hal sorgawi?', 'If I told you earthly things and you don’t believe, how will you believe if I tell you heavenly things?');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 13, 'Tidak ada seorangpun yang telah naik ke sorga, selain dari pada Dia yang telah turun dari sorga, yaitu Anak Manusia.', 'No one has ascended into heaven, but he who descended out of heaven, the Son of Man, who is in heaven.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 14, 'Dan sama seperti Musa meninggikan ular di padang gurun, demikian juga Anak Manusia harus ditinggikan,', 'As Moses lifted up the serpent in the wilderness, even so must the Son of Man be lifted up,');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 15, 'supaya setiap orang yang percaya kepada-Nya beroleh hidup yang kekal.', 'that whoever believes in him should not perish, but have eternal life.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 16, 'Karena begitu besar kasih Allah akan dunia ini, sehingga Ia telah mengaruniakan Anak-Nya yang tunggal, supaya setiap orang yang percaya kepada-Nya tidak binasa, melainkan beroleh hidup yang kekal.', 'For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 17, 'Sebab Allah mengutus Anak-Nya ke dalam dunia bukan untuk menghakimi dunia, melainkan untuk menyelamatkannya oleh Dia.', 'For God didn’t send his Son into the world to judge the world, but that the world should be saved through him.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 18, 'Barangsiapa percaya kepada-Nya, ia tidak akan dihukum; barangsiapa tidak percaya, ia telah berada di bawah hukuman, sebab ia tidak percaya dalam nama Anak Tunggal Allah.', 'He who believes in him is not judged. He who doesn’t believe has been judged already, because he has not believed in the name of the one and only Son of God.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 19, 'Dan inilah hukuman itu: Terang telah datang ke dalam dunia, tetapi manusia lebih menyukai kegelapan dari pada terang, sebab perbuatan-perbuatan mereka jahat.', 'This is the judgment, that the light has come into the world, and men loved the darkness rather than the light; for their works were evil.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 20, 'Sebab barangsiapa berbuat jahat, membenci terang dan tidak datang kepada terang itu, supaya perbuatan-perbuatannya yang jahat itu tidak nampak;', 'For everyone who does evil hates the light, and doesn’t come to the light, lest his works would be exposed.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 21, 'tetapi barangsiapa melakukan yang benar, ia datang kepada terang, supaya menjadi nyata, bahwa perbuatan-perbuatannya dilakukan dalam Allah."', 'But he who does the truth comes to the light, that his works may be revealed, that they have been done in God.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 22, 'Sesudah itu Yesus pergi dengan murid-murid-Nya ke tanah Yudea dan Ia diam di sana bersama-sama mereka dan membaptis.', 'After these things, Jesus came with his disciples into the land of Judea. He stayed there with them, and baptized.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 23, 'Akan tetapi Yohanespun membaptis juga di Ainon, dekat Salim, sebab di situ banyak air, dan orang-orang datang ke situ untuk dibaptis,', 'John also was baptizing in Enon near Salim, because there was much water there. They came, and were baptized.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 24, 'sebab pada waktu itu Yohanes belum dimasukkan ke dalam penjara.', 'For John was not yet thrown into prison.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 25, 'Maka timbullah perselisihan di antara murid-murid Yohanes dengan seorang Yahudi tentang penyucian.', 'There arose therefore a questioning on the part of John’s disciples with some Jews about purification.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 26, 'Lalu mereka datang kepada Yohanes dan berkata kepadanya: "Rabi, orang yang bersama dengan engkau di seberang sungai Yordan dan yang tentang Dia engkau telah memberi kesaksian, Dia membaptis juga dan semua orang pergi kepada-Nya."', 'They came to John, and said to him, “Rabbi, he who was with you beyond the Jordan, to whom you have testified, behold, the same baptizes, and everyone is coming to him.”');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 27, 'Jawab Yohanes: "Tidak ada seorangpun yang dapat mengambil sesuatu bagi dirinya, kalau tidak dikaruniakan kepadanya dari sorga.', 'John answered, “A man can receive nothing, unless it has been given him from heaven.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 28, 'Kamu sendiri dapat memberi kesaksian, bahwa aku telah berkata: Aku bukan Mesias, tetapi aku diutus untuk mendahului-Nya.', 'You yourselves testify that I said, ‘I am not the Christ,’ but, ‘I have been sent before him.’');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 29, 'Yang empunya mempelai perempuan, ialah mempelai laki-laki; tetapi sahabat mempelai laki-laki, yang berdiri dekat dia dan yang mendengarkannya, sangat bersukacita mendengar suara mempelai laki-laki itu. Itulah sukacitaku, dan sekarang sukacitaku itu penuh.', 'He who has the bride is the bridegroom; but the friend of the bridegroom, who stands and hears him, rejoices greatly because of the bridegroom’s voice. This, my joy, therefore is made full.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 30, 'Ia harus makin besar, tetapi aku harus makin kecil.', 'He must increase, but I must decrease.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 31, 'Siapa yang datang dari atas adalah di atas semuanya; siapa yang berasal dari bumi, termasuk pada bumi dan berkata-kata dalam bahasa bumi. Siapa yang datang dari sorga adalah di atas semuanya.', 'He who comes from above is above all. He who is from the earth belongs to the earth, and speaks of the earth. He who comes from heaven is above all.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 32, 'Ia memberi kesaksian tentang apa yang dilihat-Nya dan yang didengar-Nya, tetapi tak seorangpun yang menerima kesaksian-Nya itu.', 'What he has seen and heard, of that he testifies; and no one receives his witness.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 33, 'Siapa yang menerima kesaksian-Nya itu, ia mengaku, bahwa Allah adalah benar.', 'He who has received his witness has set his seal to this, that God is true.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 34, 'Sebab siapa yang diutus Allah, Dialah yang menyampaikan firman Allah, karena Allah mengaruniakan Roh-Nya dengan tidak terbatas.', 'For he whom God has sent speaks the words of God; for God gives the Spirit without measure.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 35, 'Bapa mengasihi Anak dan telah menyerahkan segala sesuatu kepada-Nya.', 'The Father loves the Son, and has given all things into his hand.');
INSERT INTO public.bible_verses (book_id, book_name_id, book_name_en, chapter, verse, text_id, text_en) VALUES (43, 'Yohanes', 'John', 3, 36, 'Barangsiapa percaya kepada Anak, ia beroleh hidup yang kekal, tetapi barangsiapa tidak taat kepada Anak, ia tidak akan melihat hidup, melainkan murka Allah tetap ada di atasnya."', 'One who believes in the Son has eternal life, but one who disobeys
 the Son won’t see life, but the wrath of God remains on him.”');

